name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11", "3.12"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install poetry
        python -m poetry config virtualenvs.in-project true
        python -m poetry install

    - name: Run tests
      run: |
        poetry run pytest --cov=xetl --cov-report=term-missing --cov-report=xml -vv tests
        poetry run coverage xml -o coverage.xml

    - name: Upload coverage report to Codecov
      if: ${{ github.ref == 'refs/heads/main' && matrix.python-version == '3.12' }}
      uses: codecov/codecov-action@v2
      with:
        file: ./coverage.xml
        token: ${{ secrets.CODECOV_TOKEN }}


